spring.application.name=shop-api
server.port=${SERVER_PORT:8051}

spring.jpa.hibernate.ddl-auto=none

kafka.bootstrap.address=${KAFKA_BOOTSTRAP_ADDRESS:localhost:9092}

# Kafka Configuration
spring.kafka.bootstrap-servers=${kafka.bootstrap.address}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=MANUAL

