spring.application.name=validator-api
server.port=${SERVER_PORT:8052}

spring.jpa.hibernate.ddl-auto=none

kafka.bootstrap.address=${KAFKA_BOOTSTRAP_ADDRESS:localhost:9092}

# Kafka Configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:9092}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=MANUAL

